version: '3.5'

services:
  telegram-download-daemon:
    env_file: .env
    build: .
    image: telegram-download-daemon:latest
    volumes:
       - ./downloads:/downloads
       - ./session:/session
    restart: unless-stopped